title: David Broder-Rodgers
author: David Broder-Rodgers
description: >
  Hi, my name is David Broder-Rodgers and I'm a software developer based in London. This site contains some
  of the things I've done - hopefully there will be much more here in the future!
baseurl: ""
url: https://dbr.ie
permalink: /:year/:month/:day/:title.html
paginate: 5
paginate_path: /:num/
date_format: '%b %-d, %Y'
facebook_username: dbroderr
linkedin_username: broder
github_username: broder
github_project: broder.github.io
steam_username: broder
placeholder_image: 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=='
google_analytics: UA-37851343-2
disqus:
    shortname: dbr-1
    amp_url: https://amp.dbr.ie

defaults:
  - values:
      layout: page

jekyll-minifier:
  exclude:
    - feed.xml
    - sitemap.xml

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-minifier
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - .gitignore
  - .rubocop.yml
  - Gemfile
  - Gemfile.lock
  - logos
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
