version: '3'

services:
  jekyll-dev:
    build: ./jekyll-dev
    env_file: .env
    volumes:
      - github-home:/github/home
      - ${PWD-.}/..:/github/workspace
    working_dir: /github/workspace

volumes:
  github-home:
